version: "3"
services:
  jenkins:
    environment:
      - JENKINS_ADMIN_ID=$JENKINS_ADMIN_ID
      - JENKINS_ADMIN_PASSWORD=$JENKINS_ADMIN_PASSWORD
      - JENKINSFILE_IMPLANTED_GH_REPO=$JENKINSFILE_IMPLANTED_GH_REPO
    image: jenkins
    build: ./jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always
  ssh-agent:
    image: jenkins/ssh-agent
volumes:
  jenkins_home:
